gradients:
  sunrise:
    name: "Sunrise Gradient"
    gradient: "<gradient:#FDBB47:#FF0000>"
    gui-item: NAME_TAG
    lore:
      - "<dark_grey>Gradient"
      - ""
      - "<red>Locked"
      - ""
      - "<#FE2E2B>✘ Not purchasable"
gui:
  # STRUCTURE
  # Gradient = .
  # Filler Item = #
  # Back Forward = <
  # Clear Gradient = !
  # Page Forward = >
  structure:
    - "# # # # # # # # #"
    - "# . . . . . . . #"
    - "# . . . . . . . #"
    - "# . . . . . . . #"
    - "# # # < ! > # # #"
  title: "<yellow>Gradients</yellow>"
  filler:
    name: “<reset>”
    material: BLACK_STAINED_GLASS_PANE
  page-forward:
    name: "<grey>Next Page"
    material: LIME_SHULKER_BOX
  page-back:
    name: "<grey>Previous Page"
    material: RED_SHULKER_BOX
  clear-gradient:
    name: "<red>Unequip current gradient"
    material: BARRIER
  gradient:
    material: NAME_TAG
    lore-available:
      - "<dark_grey>Gradient"
      - ""
      - "<green>✔ Purchased"
      - ""
      - "<yellow>➥ <b><u>CLICK</u></b> to Select"
    lore-locked:
      - "<dark_grey>Gradient"
      - ""
      - "<white>Purchase a gradient to make your name"
      - "<white>stand out to everyone!"
      - ""
      - "<#FE2E2B>✘ Obtain from <yellow>/coinshop."

debug: true
config-version: "1.0.0"