options:
  # If you want to use a different placeholder as the player's name
  # Uses any PlaceholderAPI placeholder. For example: if using "%essentials_nickname%",
  # %prism_customname% will return %essentials_nickname% with the gradient applied
  alt-placeholder:
    enabled: true
    placeholder: "%essentials_nickname%"

gradients:
  prism:
    name: "Prism Gradient"
    gradient: "<gradient:#9cc2fd:#aa93ff:#e2b5fd:#fdadf8>"
    gui-item: NAME_TAG
    # lore is optional, if not provided uses gui.gradient.lore-available/locked
    lore-available:
      - "<dark_grey>Gradient"
      - ""
      - "<green>✔ Purchased"
      - ""
      - "<yellow>➥ <b><u>CLICK</u></b> to Select"
    lore-locked:
      - "<dark_grey>Gradient"
      - ""
      - "<#FF0000>✘ Locked"
      - ""
      - "<#FFD700>Not obtainable"
gui:
  # STRUCTURE
  # Gradient = .
  # Filler Item = #
  # Back Forward = <
  # Clear Gradient = !
  # Page Forward = >
  structure:
    - "# # # # # # # # #"
    - "# . . . . . . . #"
    - "# . . . . . . . #"
    - "# . . . . . . . #"
    - "# # # < ! > # # #"
  title: "<yellow>Gradients</yellow>"
  filler:
    name: "<reset>"
    material: BLACK_STAINED_GLASS_PANE
  page-forward:
    name: "<grey>Next Page"
    material: LIME_SHULKER_BOX
  page-back:
    name: "<grey>Previous Page"
    material: RED_SHULKER_BOX
  clear-gradient:
    name: "<red>Unequip current gradient"
    material: BARRIER
  gradient:
    material: NAME_TAG
    lore-available:
      - "<dark_grey>Gradient"
      - ""
      - "<green>✔ Purchased"
      - ""
      - "<yellow>➥ <b><u>CLICK</u></b> to Select"
    lore-locked:
      - "<dark_grey>Gradient"
      - ""
      - "<white>Purchase a gradient to make your name"
      - "<white>stand out to everyone!"
      - ""
      - "<#FF0000>✘ Locked"
      - ""
      - "<#FFD700>Obtain from <u>/coinshop<u>!"

version: "0.0.4"