name: Prism
version: '${version}'
main: dev.dxnny.prism.Prism
api-version: '1.21'
authors: [ dxnnv ]
description: Color your displayname with custom gradients!
website: https://dxnny.dev/
depend: [ PlaceholderAPI ]
default-permission: op
default-permission-message: "You do not have permission to use this command"
commands:
  gradients:
    description: "Opens the gradients GUI"
    usage: "/gradients"
    permission: prism.use
    aliases:
      - gradient
  prism:
    description: "Main command"
    usage: "&e/prism <help|set|clear|reload> [player] [gradient]"
    permission: prism.admin
permissions :
  prism.admin:
    description: "Access to /prism <help|set|clear|reload>"
    default: op
  prism.use:
    description: "Access to /gradients menu"
    default: true