name: Prism
version: '${version}'
main: dev.dxnny.prism.Prism
api-version: '1.20'
authors: [ danny ]
description: Color your displayname with custom gradients!
website: https://dxnny.dev/
depend: [ PlaceholderAPI ]
default-permission: op
default-permission-message: "You do not have permission to use this command"
commands:
  gradients:
    description: "Opens the gradients GUI"
    usage: "/gradients"
    aliases:
      - gradient
  prism:
    description: "Main command"
    usage: "&e/prism <set|clear|reload> [player] [gradient]"
    permission: prism.admin
permissions :
  prism.*:
    description: "Wildcard Permission"
    default: op
    children:
      prism.admin: true
      prism.use: true
  prism.admin:
    description: "Access to /prism [set|clear|reload]"
    default: op
  prism.use:
    description: "Access to /gradients menu"
    default: true